spring:
    datasource:
        password: 
        username: sa
        url: jdbc:h2:mem:testdb
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
